package app.pursi.datasource.core

object VesiLiikennemerkkiIconMapper {

    fun toIconName(vlmlajityyppi: Int): String = when (vlmlajityyppi) {
        0 -> "josm_Q126_generic_crossing"
        1 -> "josm_Q126_BNIWR_no_anchoring"
        2 -> "josm_Q126_generic_no_berthing"
        3 -> "josm_Q126_generic_no_berthing"
        4 -> "josm_Q126_CEVNI_no_convoy_overtaking"
        5 -> "josm_Q126_CEVNI_no_convoy_passing"
        6 -> "josm_Q126_generic_speed_limit"
        7 -> "josm_Q126_generic_no_waterskiing"
        8 -> "josm_Q126_generic_no_sailboards"
        9 -> "josm_Q126_CEVNI_no_entry"
        10 -> "josm_Q126_CEVNI_no_waterbikes"
        11 -> "josm_Q126_generic_speed_limit"
        12 -> "josm_Q126_CEVNI_stop"
        13 -> "josm_Q126_generic_crossing"
        14 -> "josm_Q126_generic_make_radio_contact"
        15 -> "josm_Q126_BNIWR_limited_headroom"
        16 -> "josm_Q126_generic_limited_depth"
        17 -> "josm_Q126_generic_crossing"
        18 -> "josm_Q126_generic_crossing"
        19 -> "josm_Q126_generic_crossing"
        20 -> "josm_Q126_generic_crossing"
        21 -> "josm_Q126_CEVNI_radio_information"
        22 -> "josm_Q126_CEVNI_berthing_permitted"
        23 -> "josm_Q126_CEVNI_berthing_permitted"
        24 -> "josm_Q126_CEVNI_overhead_cable"
        25 -> "josm_Q126_generic_telephone"
        26 -> "josm_Q126_generic_ferry_independent"
        27 -> "josm_Q126_generic_ferry_independent"
        28 -> "josm_Q126_CEVNI_radio_information"
        29 -> "josm_Q126_generic_drinking_water"
        30 -> "josm_Q126_CEVNI_prohibition_ends"
        31 -> "josm_Q126_CEVNI_overhead_cable"
        32 -> "josm_Q126_CEVNI_overhead_cable"
        33 -> "josm_Q126_generic_alignment"
        34 -> "josm_Q126_generic_alignment"
        35 -> "josm_Q126_generic_crossing"
        36 -> "josm_Q126_generic_crossing"
        37 -> "josm_Q126_generic_crossing"
        else -> "josm_Q126_generic_crossing"
    }
}
